### ISSUE TITLE
Compile a set of questions to be discussed with Prof.Hall on Fri, Sep 6

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#11]
- Gather more resources to learn the fundamentals about RAGs and LLMs
- Where are we building the RAG database? What sort of DB should this be - structured/unstructured/semi-structured?
- Learns more about the stakeholders and their personalities. What has worked in the past? Any red flags?
- What could be the nature of data engineering work involved in this project?
- Do we need HPC resources for this project?

**Comment by Tendaiishe** [comment]
i have added some questions:

- How do you recommend we balance meeting the client’s expectations with achieving the academic requirements for this course?

- Could you provide insights on the potential complexities of using GraphRAG, and what should we watch out for when implementing it?

- How can we best present our final report and codebase to not only meet academic standards but also impress the client with innovative insights?

- What ethical considerations should we be mindful of when designing LLM systems forhigh-risk domains, and how can we address these in our project?

**Comment by arnabraychaudhari** [comment]
- Discuss the outstanding questions with Prof.Hall on Sep 10, either F2F or through emails
