### ISSUE TITLE
Get the Client Questions reviewed by Prof.Hall

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#13]
Meet Pro.Hall during his office hours on Fri, Sep 6

**Comment by Tendaiishe** [comment]
i will tag along

**Comment by arnabraychaudhari** [comment]
We met Prof.Hall during his Office Hours on Fri, Sep 6. He has reviewed the Client questions and entered his feedback in the G-Drive spreadsheet we shared with him.

**Comment by Tendaiishe** [comment]
i will do these
