### ISSUE TITLE
Meeting Rooms

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#14]
- Book meeting rooms for Client and Internal team meetings
- Bookings should be done 1 week in advance (preferably 2) to secure the rooms

**Comment by Tendaiishe** [comment]
will be responsible for booking meeting rooms for both client and team meetings!

**Comment by arnabraychaudhari** [comment]
@Tendaiishe I am closing this task since we are already tracking the same subject through task #15
