### ISSUE TITLE
Set a reminder for advance room reservations at Gelman

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#15]
- Ensure rooms are reserved 2 weeks in advance for Client and Internal team meetings at Gelman Library

**Comment by Tendaiishe** [comment]
I will be sure to schedule and add room reservations and reminders to your calenders.

**Comment by arnabraychaudhari** [comment]
@Tendaiishe You may not be able to book all rooms for your future meetings now. But, if you added the reminders (which are meant to remind you that rooms need to be reserved for upcoming meetings) to your personal calendar, then we can close the task.

**Comment by Tendaiishe** [comment]
Sorted out
