### ISSUE TITLE
Client Meeting Slots

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#4]
Agree on recurring weekly meeting slots to be proposed in Client Introduction email

**Comment by Nilgunaslanova** [comment]
#closed

**Comment by arnabraychaudhari** [comment]
Client proposed the kick off meeting either on Sep 10 or Sep 11, 4 PM ET
During our kickoff meeting we must also enquire if the same slot should be used for all our recurring meetings
