### ISSUE TITLE
Project Tools

### ISSUE THREAD

**Issue by arnabraychaudhari** [arnabraychaudhari/arnabraychaudhari#9]
- Setup the following tools and grant access to project team
- Communication: Slack
- Project Management: GitHub Project
- Version control software: GitHub (to be agreed with Clients)
- Documentation Repository: Google Drive (to be agreed with Clients)
- Internal Meeting recordings: Zoom
- Documentation and Presentation: Microsoft Office, Canva, Draw.io
- Setup MS Teams for Client Meetings. Verify if recording is possible on Teams

**Comment by Tendaiishe** [comment]
i am creating the teams

**Comment by arnabraychaudhari** [comment]
Status Update:
- Reached out to GW IT and acquired the instructions to integrate MS Teams meeting link with Google calendar invitation
- Performed a testing round with Tendai by setting up a meeting and subsequently recording the discussion
- Shared the MS Teams recording file with Nilgun who will setup the recurring meetings going forward
- The project team has agreed to use MS Teams as their internal communication tool. Client communication will happen over emails and online meetings through MS Teams

**Comment by arnabraychaudhari** [comment]
Status update: This is done !
